stateDiagram-v2
    [*] --> IDLE
    IDLE --> CONNECTING : New Demand
    CONNECTING --> ACTIVE_CONNECTION : Connection Request
    ACTIVE_CONNECTION --> CONNECTION_ESTABLISHED : Connection OK
    ACTIVE_CONNECTION --> IDLE : Connection NOK
    CONNECTION_ESTABLISHED --> WAITING_FOR_REQUEST : MODBUS Request
    WAITING_FOR_REQUEST --> PROCESSING_REQUEST : ValidateRequest
    PROCESSING_REQUEST --> SENDING_RESPONSE : ProcessRequest
    SENDING_RESPONSE --> WAITING_FOR_REQUEST : SendResponse
    WAITING_FOR_REQUEST --> WAIT : Timeout
    WAIT --> PROCESSING_REQUEST : Retry
    WAIT --> IDLE : Timeout
    PROCESSING_REQUEST --> DISCONNECTED : Error
    SENDING_RESPONSE --> DISCONNECTED : Error
    DISCONNECTED --> CONNECTING : Retry
    DISCONNECTED --> [*]
```